type: "probabilistic"
encoder:
  backbone: "resnet18"
  latent_dim: 128
  pretrained: true
decoder:
  use_decoder: true
  image_size: ${dataset.image_size}
verifier:
  hidden_dims: [256, 128]
projector:
  use_mlp: true
  hidden_dims: [128] # Optional, defines intermediate layers
  activation: "ReLU" # Chọn hàm kích hoạt, vd: ReLU, LeakyReLU, GELU, SiLU
  proj_dim: 64
