type: "probabilistic"
encoder:
  backbone: "mock"
  latent_dim: 128
  pretrained: false
decoder:
  use_decoder: true
  image_size: ${dataset.image_size}
verifier:
  hidden_dims: [128]
projector:
  use_mlp: true
  hidden_dims: [128]
  activation: "LeakyReLU" 
  proj_dim: 128
