type: "unet"
encoder:
  backbone: "palmnet" # Sử dụng kiến trúc lấy cảm hứng từ PalmNet
  in_channels: 3
  palmnet_gabor_init: true # Sử dụng bộ lọc Gabor để khởi tạo các trọng số của Layer 1 theo chuẩn PalmNet
  latent_dim: 128
decoder:
  use_decoder: true
  skip_dropout: 0.8
  image_size: ${dataset.image_size} # Interpolate from dataset config
  unet_channels: [64, 128, 256, 512] # Default U-Net channels
verifier:
  hidden_dims: [256, 128]
projector:
  use_mlp: true
  hidden_dims: [256, 256] 
  activation: "LeakyReLU"
  proj_dim: 128
  use_bn: true
