type: "unet"
encoder:
  backbone: "cnn" 
  # Cấu hình siêu nhẹ (lightweight) cho mạng tích chập
  hidden_dims: [16, 32, 64]
  latent_dim: 128
decoder:
  use_decoder: true
  skip_dropout: 0.8
  image_size: ${dataset.image_size} # Interpolate từ cấu hình dataset
  unet_channels: [16, 32, 64, 128] # Cấu hình số channel của U-Net Decoder (c1, c2, c3, c4)
verifier:
  hidden_dims: [64, 32]
projector:
  # Cấu hình Projector nhỏ, gọn
  use_mlp: true
  hidden_dims: [128]
  activation: "LeakyReLU" 
  proj_dim: 128
  use_bn: true # Bật/tắt BatchNorm1d ở lớp cuối (Tuyệt chiêu cho ArcFace)
