# Chọn hàm loss: 'supcon', 'ms_loss', hoặc 'infonce'
contrastive_type: "ms_loss"

# Cấu hình cho MS Loss
ms_alpha: 2.0
ms_beta: 50.0
ms_base: 0.5

# Cấu hình cho SupCon / InfoNCE
temperature: 0.1

weights:
  lambda_id: 1.0
  lambda_con: 0.5
  lambda_pair: 1.0
  lambda_rec: 1.0
  beta_kl: 0.005
  lambda_unc: 0.1

