epochs: 30
batch_size: 32
num_workers: 2
learning_rate: 0.005
weight_decay: 0.0001
optimizer: "AdamW"
scheduler: "StepLR"
scheduler_step_size: 5
scheduler_gamma: 0.1
log_interval: 10
save_interval: 1
use_sampler: true
sampler_type: "pk_sampler"
sampler_p: 8 # Number of different classes
sampler_k: 4 # Number of samples in classes

seed: 42
accelerator: "auto" # options: "auto", "cpu", "gpu", "tpu", "mps"
devices: 1 # number of devices (GPUs/TPUs) to use

# Dùng để chạy tiếp checkpoint cũ
resume_from_checkpoint: null
