name: "iitd"
data_dir: "data/IITD Palmprint V1/Segmented"
image_size: [150, 150]
channels: 3
num_classes: 230 # Giả định IITD có 230 người

# Chế độ ratio: Gộp Left và Right lại rùi chia tỷ lệ 80/20
split_mode: "ratio"
train_ratio: 0.8
seed: 42

transforms:
  random_grayscale: 0.5
  random_rotation: 15
  color_jitter:
    brightness: 0.2
    contrast: 0.2
  random_affine:
    translate: [0.1, 0.1]
    scale: [0.9, 1.1]
