name: "OwnOriginalDataset"
data_dir: "data/collect"
image_size: [128, 128]

# 'both', 'left', hoặc 'right' - dùng để lọc thư mục con nếu dataset có chia tay trái/phải
hand_filter: "both"

# Nếu bạn muốn cấu hình thêm các tham số data augmentation khác thì thêm ở đây
transform:
  resize: true
