name: "OwnOriginalDataset"
data_dir: "data/collect"
image_size: [128, 128]

# 'both', 'left', hoặc 'right' - dùng để lọc thư mục con nếu dataset có chia tay trái/phải
hand_filter: "both"
split_mode: "ratio"
train_ratio: 0.9

# Đã đổi 'transform' thành 'transforms' cho đúng code BaseDataset
transforms:
  random_grayscale: 0.5
  random_rotation: 15 # Giảm từ 30 xuống 15 để không làm hỏng vân tay (sinh trắc học)
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  random_affine:
    translate: [0.1, 0.1]
    scale: [0.9, 1.1]
  # KHÔNG dùng random_horizontal_flip vì lật trái/phải sẽ biến bàn tay thành tay của người khác!